apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: headlamp
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      version: "0.36.0"
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  releaseName: headlamp
  targetNamespace: headlamp
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      hosts:
        - host: cluster.icytv.de
          paths:
            - path: /
              type: Prefix
      tls:
        - secretName: headlamp-tls
          hosts:
            - cluster.icytv.de
    config:
      watchPlugins: true
    pluginsManager:
      enabled: true
      configContext: |
        plugins:
          - name: headlamp-plugin-flux
        installOptions:
          parallel: true
          maxConcurrent: 2
      baseImage: node:lts-alpine
      version: latest
      env:
      - name: HOME
        value: /tmp
      - name: NPM_CONFIG_PREFIX
        value: /tmp/npm
      - name: PATH
        value: /tmp/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    persistentVolumeClaim:
      enabled: false
      accessModes:
        - ReadWriteOnce
      size: 1Gi