apiVersion: v1
kind: Secret
metadata:
    name: oidc-secret
    namespace: headlamp
type: Opaque
stringData:
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:FjbKEaiUsgYiZ26QGximl0kUKMx4hMD6f2vFtxvKsYKyrh4ElLoi,iv:hk1cYH0kyv5C7CGCyLHnanARlbT38GMXJ780v8o6y3M=,tag:hxa/f0aGSr8hGfzyXM9UhQ==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:ydI6MxhG+rpOFPQ3xl7hm+4Sg1YfBvk0z0gW,iv:IUxky6hznbEjHttPgAmcV5m1Vd+YJiQaxvSq9A9eC2Q=,tag:TECFlWs8JSQ9aGi4OW3/VQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:tM1kz38mS5XYm+y68uPaPNG5iRWPHKvTCxnEtB1t2EaW1ufh1MkoUQ==,iv:Y2yHAQtXouKeoFN/ahla+AFjTSDs/mdpSrYPKeKAj14=,tag:PCrOuziNars0zqdZ7idQlw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:LkhNFMIe41amwB60y8iugiKTfVlsIyl1H6lQUqspa/UdSXFdYlAH6HiNNG6b7aO3Fi0JfN8pzrCiI9F41LiBTZYOa2tDnyIVT0iemQ+nM/afIyY0bBg4DQ1Wr/XYzzJnnGa0Kj0icKA7AQ7/pugDlX93xiKIIKWdujuPTeteII8=,iv:0gmSdHlH2gpHQ8vwrS/G2yzfsq0ulcrDXodRQeAm/c4=,tag:TwPmkgwQPULF+yjhjLFr6g==,type:str]
sops:
    age:
        - recipient: age1jp7ddpkrycjnwj9slrv0hm3g4alj259df022gj6pcf2v5pnj4vuqswulmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbXJ1ZVpZV2pKcDhocWNl
            MG5PQytPQUh3cERhMk9SWGZTYkN1QVp5RldJCk5kVWpQcUs4NUI4aVllYm1IeHcr
            RnYvVTFHUmJLTHMwUk16eVdVaWhnQ0UKLS0tIHJIL1poUFhGcDQ0cjVWTFdPODlG
            R1BrMEt0SGFuNEJxOHBya21XRUdNamMK5D+hHdoUjLJ+fa36V+SRYJqZHWbd2R/x
            QXqZ9hyGwvM+DsB1TMvJurSt/WpalyLNdIET/nX1MH9HF8kiNgE2LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T11:31:14Z"
    mac: ENC[AES256_GCM,data:9c3T8mKRHb3K9YHgfL4g4spbTbZO4kXAcZkXMcFclSdXrYaFENojV9IN3hnccFm+4GiXfRy3eFY/rp659r5ZBm9pOrFM+u0xFPnasXoYaY//uZbx9zUBCHlf05komcc5FfrK5OMAhQ6toC1EF5X4P1t8gho8yrJkl993bCgm5aE=,iv:gg9GDAR9hY9Vfxex55e8W2VEMgyvUpZH3ALDyNn42+4=,tag:bzauaUZ+YhMoyAb/K83uBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
