apiVersion: v1
kind: Secret
metadata:
    name: oidc-secret
    namespace: headlamp
type: Opaque
stringData:
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:h3xWc3Fn8PyrBxwhfHxlRo/7jx31qIStM1X3lXIu08L1GRE/iY/knte0cK1l,iv:obZ3R9yZY5tZasA1kIiT65lW3UI/YUZWD2b40R+gS9E=,tag:SS8K+piNjTImNhp8thrNmA==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:ZacQLBj+w/OlYBmG9CwfdOgIxQw=,iv:gf7U17CRVrZVRxQ1BMqRMtALDs6iFyLs4qyXh+S7Ev4=,tag:IXp5Uz1c3e9KEW+eDCKHzg==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:+p6pDTVD066k/yw+fcv8SmiXxPCzo+yAMaN6accL6Z0sr6kttA8fxg==,iv:TFufqpD8WP+7n6CBG0XwHWBgX8l25C2ntUBXSP6yCqs=,tag:H6erHeNCTgzsKBH8R0pY0w==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:SotNriz14GweInLeKLl6W9U3wI9Jj5/lv6Isf+nT2w92Rov7DMv3P+znD96T3DeTJykhAsweBiSZAn2iYn/2n5w7oE8QO5mqTa85LrKNpWS4KNj2QF6eNRTPU1qyMBUSgqvBUWPgkIbueEgo6iL3BbwNUU5kUGvau+tcsXCq09s=,iv:nrxTTtnHhAmnv+jaaOfjDWzoDEkinHD+0yWsTaZggvM=,tag:4ZuhKrySvdL7Np9Gpaf8MQ==,type:str]
sops:
    age:
        - recipient: age1jp7ddpkrycjnwj9slrv0hm3g4alj259df022gj6pcf2v5pnj4vuqswulmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TjZpMHA2dmUvK3NEb1FO
            dWVCckFmOU4ybGJnMGt5YjVxVmo1emNac21VCkRWSUkwUjdDZjhYSDlQZjN2WEFU
            ZXdSckpVK3p5MnpXYUE0eGp4c29iVlkKLS0tIHA1UldJbVNObndySnI2bE03TXlr
            Q1lyYngxckUwS2s5S1AvU3FWVTJBUWsKCRJ3OvHnqvxBvS2us2m213fAQFO0cmKt
            ctBQEg5q1B9iwPc6FnDvz+TnLEVp+KP9gJl5H4mreTGJWGpgNO/2YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-30T15:26:04Z"
    mac: ENC[AES256_GCM,data:ymEjcpZWHa2tArDkqbf281jjMnEt6ZLWB5XvFn0z5TzlNqFkoDfrAKfsXnLZU0AiZmeHvvjGMKeI9LmdPm3R4xNPeDs7QCRp95GmNTm5952RYumflEOr/h17OKp8Evi6rSdyRH43Tcu6tFjr3T+YMF3qPg1lo61WVBZFVkVRFs8=,iv:qM79HwEwvX6kr/bW34hDy8PGTnls3hb23TqHB7ExqNk=,tag:pAGgykTYMr7IXO44rkNw2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
