apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: "v1.19.1"
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  releaseName: cert-manager
  targetNamespace: cert-manager
  dependsOn:
    - name: namespaces
  values:
    installCRDs: true