---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgCVf1xCqvH93uBMX5rezNqH5AOgNuYUXvW1snpwHwI5gEyhfqlWT2n8r7wmdfJUVG9wUma8Y+yhpoycWI26lASADAd8RithubAFe83SFvQhauKZy4FTzP66pSsZ/zMHj8xFvTiBNI0q4/PqAFg4jqt1aSFGx/HyF4pLz2EWr2B0IYcsX2WSm8serwKYkCq1ri9BfVnKlQZT81p/7TvYkyna/7R418yWhHE7tY9EXs4yROTVrlhfc2VZY/9RURtuLkOGgGUFgkZLfkklJpHsm3XSgfQ60mLNNjacHVCq62CTq+cFnEGYAVoxv15S4d0v7lCfyEUtjZ1Fcj9wyeS675lTGX3l3aSJ338UF+Tb50Upk5OCxGQRdOdF9D+tVILZMGMDXO+n3mk3b4r3Z/0jdPuZZI/e2SWZZ6oZOaxlDQvBgCwy5qzuzXg2LPbQjTpwJ9/jA4Mcenei/VFVAkjuQnt9fU8hb0B5qiB8mOo/2zdMKsYocPlJi2l8nGumZm1eXh7/OdJQK3V6qotZLZu7UutY4aRH4J341VMShQJIAprnEsAaQdT2oedu/NR6q1C4uTmN8QnXgrxkAUwTucLdGtC8/6JgTygCGB9e1TJGOv+DZ3XZpBf0Exr2i6OiFTySFBceahjD3sHsNgkiFpNSnxG5Ip8X9+RN3jEmcbOqFgOqr41E+863eGUZOMtF7CINRfq+JyTw/9L4lBm3LBKJjgemKK8XJcubFESKX4V7izRRmZuL6w9Nid2hwFSTMuCqrOwt8nthTNEDc4/CZoNmbLZYCPbrnW6uaYLTAQirij/OeKmjR3sQ1BYm22YrgHUvKcJJZBl6KthLw1bFu/SDqvPV4KuwdZG+gLywty43wkLoiSu+bzxJ5kUgdwtTl/t28cQa0l15RnO3zAoB7hRQp69gF0/InNfDtxLwhMd3w4ZJ
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
