apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      version: "2025.8.4"
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  releaseName: authentik
  targetNamespace: authentik
  dependsOn:
    - name: base

  values:
    server:
      ingress:
        enabled: false
        hosts:
          - auth.icytv.de
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: secret-key
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-postgres
              key: password
    postgresql:
      enabled: true
      auth:
        existingSecret: authentik-postgres
        secretKeys:
          passwordKey: password
    redis:
      enabled: true

    worker:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: secret-key
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-postgres
              key: password