apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: namespaces
  path: ./manifests/authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  target-namespace: authentik
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: authentik-server
    - apiVersion: apps/v1
      kind: Deployment
      name: authentik-worker
  timeout: 5m