---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  encryptedData:
    password: AgCKfVHroH9UhnHx5BJQG65ao9u3Duj89JVyxBHhc7RU/cOu/fvSlKLcG6NfXLbDYJtfJ2yoUaYWeQ96hM0d8tQiFETZRuLu8G1Ik7QZVDsESDNZ6O5jhV+UoCqbXGtCvgQXuO7uH8CtD6zzYD9tkWiA7L6UtXzLzfc81GU5DunATr15NKlEHVW5+5cqoxURJRsr1W9w4Po9ysRp6ml+UWWVyIGZu+jTqlq8hylnVnGZpga0kR62Jy+Nw8pipircwAJbRj42WWSnIzIi+Pm15paZ/UwnFFU/6LzWY6+S9VokQAyKVT1VJAKIx3RHu6EmgegaSDiGhkWrAyjU6WE/YZj6qd8BRXTPfok1pobdAEvVIuloG5OrT/vc0SCMlRpr/mfU/vFxEdOs8+Ak/rfoD4QchQFxOHbWYYZoLwutHPr+DayM0fSWorvMCG/ZzgC1OWvY4FUO1Qs95OcVN1QcLYb8YzcYNTTDtEB8IyCmndsVh/NXzSm6wHBJ4PRJ988Xt2ABsplBuLxTA1C2spaSemS0UuNemdR3QPk0TE05gHSV9vuEsV6HTWIqM/pzEaPvIp9I7e00OkSqGSupdA7FXSUqjjtiIQG75VRFkpDwcP69vGRA/hzSdQANKOYzg/i3naf/n/T2X3rPlqPIdc1SJ+Al+rIbGAeuHXndlRgWI22AW0BWBc5GTjLqmah6o9GrRaXU4oazg53OJRjJblm8oYlmtRDtjVp9i8POAvnkFs+O0lKfZu6B8JjqbyMjHvpeP8n67Ey+g1vbJXz1FCQAA2fY
  template:
    metadata:
      name: authentik-postgres
      namespace: authentik
