---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-key
  namespace: authentik
spec:
  encryptedData:
    secret-key: AgCjTu4sykXYXMyPDQlVLQXR8uREwh2ItHS0lYLROXk8UO+MPblaLmGzxVVNW8LEUZxNksu3WJ1BGyYBFaxkke//+mQw3R4RWllcZVAdMG00e9eplcW+ApflyJP4dcW9Q4bfg8/4HLY7fDY26nfhYELrcJoGICVt5Nl9gSNyPcnwg+o9rUEBDZ7g84txrxT1SXd8T33L2Rj1YG7xmBMHanATf267Ojy5+lWhwPvkisVFfYU8280zHVrYUQLc3etWE5t3C1h137aO+a61LD4RXdv1BEPybd00/7bWnSufltEFhbGB297aVh4kj6N4QA8TQY385kj2aFQzU9izGeYl2gXK6IvUCO5G7fKFG/xAQjGadzg21sHZ5mg06xgm7rEdD++6PMTaYT9Tl7kmHCICN73+6HqSHW15Zd173c9ucKyodut55PHi9c5HvIm8EBpNaoMK6t+sqK3QLhPQwixOyHo4YE3WFR/2u4qeh0t8G74rv7HIUywYdIENTcGBmZEh6WbhV5rX4YHFecXt0qBC5tF4zbRwlRLubtAIG+5NilL/kKTujrv61FJecPzeMrmEiofOp9gAccrS4lFo4HCJMJipfJhRV/8uCqPTYYAqY/tuqtuJri+iHzzEmSP/UnUNbZUUyWcOBoZ8LHTTmdAEES9TTF90J+GYzxTyvIWigf9okVQlBTQWZAYirO7usCDwN3802aT4LMDs6YQoY1jsNkICURVjj2FNQRN5zvFTioOBLKsN6b7tqVobuRPN5Q==
  template:
    metadata:
      name: secret-key
      namespace: authentik
