server:
  ingress:
    enabled: false
    hosts:
      - auth.icytv.de
postgresql:
  enabled: true
redis:
  enabled: true
server:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: secret-key
          key: secret-key

worker:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: secret-key
          key: secret-key