server:
  ingress:
    enabled: false
    hosts:
      - auth.icytv.de
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: secret-key
          key: secret-key
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres  # The secret we just made
          key: password            # The key inside that secret
postgresql:
  enabled: true
  auth:
    existingSecret: authentik-postgres
    secretKeys:
      passwordKey: password
redis:
  enabled: true

worker:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: secret-key
          key: secret-key
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres  # The secret we just made
          key: password            # The key inside that secret