apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:daVzqc40qQwx9vQdzWUXXA/9p3tvGuzVbNBS9abYK0+6BYsK6T/tU1iE/qhFRKzAdjtNzWF0W0qld6ytBdM=,iv:+0RZh6RqxHlXwd0kpXPUemZ2ta7Ef/CpMADUy4tT3yU=,tag:XhXdaO6DDJx8CK4cFsFwcw==,type:str]
sops:
    age:
        - recipient: age1jp7ddpkrycjnwj9slrv0hm3g4alj259df022gj6pcf2v5pnj4vuqswulmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdkJBSGNLaHlncW9TOUJk
            MnhGTWV4WjNURS9tbWVRMSswZGJoYzNpdzFFCmVPTTlMbEFnYkxha2xxclJZZXFG
            WVJjMlFFUWRtWWlodmRSMUpFd3h4T0EKLS0tIHY1ZW9sYktmcU1oRFBFRnplZnVV
            bjRTWGppb3N0bGZ4ZlBtS1NJMXIzeEEKzPY4icYdOYZDxKFppKc6/We9ZgPL+uHG
            RhN0ORNSnAW+YHbd8e1SwcL001zBb4e/ZElkcV64mNKgFOJhp8lgag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T15:03:41Z"
    mac: ENC[AES256_GCM,data:r1/iUONwr9aqLB1J+33fyjC1RjqW4ARkQuMHiFkstDV4dHTXCnDosIIZbXTYRdhnRI0q0BEWh0UcLW/mHkSlJPj299+/6qaqoIZjBxJTRu4b+jzrtJ+cM991psDa5ezYwxmlcCkywzCop1Si2budFXt5Kju3iv/FS14vPZZm6TE=,iv:rKeRNjKmfkDki7l5mGl6Ms9NB0QtvswDigBnjuC9MtU=,tag:+FbKlMcmS30JgnJTD97+ng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
