---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-redis-password
  namespace: argocd
spec:
  encryptedData:
    password: AgBTHHbnrc+ArtB7a2tYo7p/MWBBWqFPIjZSsrxSxZT042BbwVOWDUlskBN2Pz/Eu4DmyYtBzya3XsmMZwQDQ6PYe+1fm7I+TBKbMcE5+h0zgmKqWKEUITcpGBL7i9cSAAqYcUL4XcLCWxFvWCeP/D72T5+qn/WRTHGSvTgu+BNsYV4x6VuCCvmZB97LVYznJRIj3gl4Uzz+W3WCO75lu6oX8NtsixJAGQLYQxxtB4DG41xdvtCoETSY3h6Uvedyubla6EZgsqAmi1TjeZP7V0avIz27UTpgRu2e89QtvkBPzkQNOUabBWH23woXsYOdzX8vhnI6PbLdNn79G7ZgyeNwx3d+X3zEyuh0yILxUZOjroANFH9akRHfUFKDpfInNOE/L02tqlcuAUCZkUizqP4Al3+gqHEBcfvLJ3JG8xlfjglneuHrMZjWnARRVcUXP6TPuanlV6FGAw9OugsVQhQIV/U0n3ncUKXsZoM/WQN1v5+++/JtDyoV8hm7jzTSpp55GLIzRzPuHGIrgQLI0YswV66Ft/ft8Xvq0gPa5VxxL5i2CZQFd3/heTYUM4b9MECEZDVb+AC01M+Jg1u+85CEpTn8RXoSBR/RRVzpfKVPkazu1mtkg2VnJL7JCgomcRq69f0IxQVMWLb0EnD0c2+9nYF9ed64PN8hZN4FoPSpggceb6c5UT6zcCgccl4VIxmtJeUP79pFcY6540MGdgBseCeXyf+EpHTXQiNOTmlcTHfKR0+yDJi/s5ZfUA==
  template:
    metadata:
      name: argocd-redis-password
      namespace: argocd
