---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-redis
  namespace: argocd
spec:
  encryptedData:
    auth: AgANp64sm/gQMxVdzaQZ71eGeZStjlFGfb3l7uedH00bYGEnbc1cliY3wIyZ/0GKH2wSD4z8nX2gvZWomf5V5Ueex/VAykbVpF5GCKL9GVqNjjsBhYbL8bpFPCWQEqFI2lnOnxuR6mniaG900x3msg7M5cdbz1KdqGahbkVBMoxCTGQYer8VJqq+MxLxl1+6nQK+TeCrU9QofTTxnj3yxQWwi4W8Z0HQL/Yd1TAWqDzNEamAI0kbwvNCFBjZcxaQ9i0MnVt+w61+dCqtN0mUMktHAlreoah9Ft5GHjd140QX4xo+qVkI4AHZN5EhBB6ZdLmwybuvunQH0aYHG8niAnyyD+E9bSSzJlL37Eblwa6BXBmrCkvm4dDpu6VBn9HgSLs6kzSD5L2zkt1lq2k3M/8CDfrSoAW3DyJaPQJ2zAnKGcEZwCob8CKVCagio7xJtIDeKloBCgeC0Fkg2h8nQ2aUkDDuufeBz910Mbg4k2rzXq/usIQ4DViAAkkXsPbF69eEMdCcpyA7SrBQaIbl7hL4YiC/0NvtrMCTlX6GNMPEHIklNerAn5V+opKf2mj251yHs5A/IX9oxDl1v5It58calppIvRe8fbnPdbZ6RqgyinKC56o0WHWUf8C+XhSQGxb8SlKhzSWjJOc35pwkvaj334dFfxUrCWrynQ9deV6mYfgiGeZsKUkpXXJKpZ8igK/ppv99AqNP1Et1Mmo9e105CpVDJ0VBIrC5ihn5vELHiGyQbuulXo2ooygNkQ==
    redis-username: AgCa/AJIOqHBBbdOeXhqVdwM1F2EuCsDcydDaOGhY5CR7oNSn25JDUXMPo6QJCsnHpqBEPWvWd2IskbKle7aTlng3QZaU9gIPF94Ru3TZREjutBpEinyGkmeM6brH3CsfsrzGD8bCP3C8z7kMrVsUjpNjSHwHJciVi+CeD4BW2lEMDq02btlYptgJaEthLTf5bD5oIWW//C7NAbk4DqJofXuLoFYs3cBcaIEnrojXGQS8jcC8miSddIsHfnz0cOzKIWiwy9DVB5YXmP2il2y3EFl2zzlgH21GuyJO+RXPmNpbvtfqs9+BFjzLbaUIq2zU9zS/iD0XMExJDaD0L2eXMJK4g7qWSM00spTPsLA9oHpcYhG4UluJh0kO7Bt0XrwGQFOzlPy5oK1Tkfh7nNhjjeCBMU+bICXeZrllHfTdiKOkATcYI6K6R7H65wBppMATE63ZnUQivTPB/Ko/Q4OaJ3RFbOCKVEZ2oH4VLBgtWfxOY0Q+iaCqSLCVu/zouI0SdX7XvCGevANcgOwweTaJcvfW1Z09ufTckY7uxqUYWDDzRrj8hCwelMcbgqUXv6i7npph5fxU0WmbdcOKNT6nTHTCMkfdXviuOp0zhCZrljr0B7TcdaL9jYGlKQTrswJkLx4urUksNQN/cEEE/p9ihysMaa6RvEITqTICQ0BaCUd+XszhaKiiq8CNKEeHnhnMupOaRbZvQO+
  template:
    metadata:
      name: argocd-redis
      namespace: argocd
