---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    server.secretkey: AgCIhK6yv2PqVhBjUv+ZsOgg30JvlEfnfOcpPMUYIAomll7VEUrKfPOi10CVo5Y933neWkTkl4f8f+ez/jT04WSyUeSOz3h6Nl1gaZi9os1xdEmDnyrFd/H7JNKDiwPxz+k7AlItIhBULboQ5gvpR+y+ymn9HsyikI63RCQC2ey2qQ6/RtZBFPWWiKHu2i05Eh/MbQHsgTWYCas46VyI64QfiqL3KoFq9bqtleEUWyyx3nt8yVTGA1mBzDtCsMLlK+QCFIslvCZ0hlpVc4GBrKnVnFaucmmGrQAyCdxLcqxCiwv0IlNWseQOykE4f9zRwFiwf3/ix6RG82C+mmVrm7NEMc3ENSu2fEyrfRkgGtm5PdNdlrPe/MXG5ZWYeJDqU4Yk2Ydv5aGO8V0Kvqxf6UYvWWRV5Z8ATuTGX3ojbu9Hekd2khV24RB4SMn3SgQbUGnF1FYrMcCb51/UJ41HUysKZYDQGDUP61mLlcNpVg/FnNeb2PiSXbwq1yDjpe7IdWOECWS2LArqU0HyQmpf3l7827pS32WG7rQOC4vMrvbu3JKh3ociRQ2fjzf2qp/YsuBHD+WFtDg+XunG7aRR4T4O+pApEzxWW1Tp6Jsik32lVaYo3LFLrQe1C1g2s51ldLcYtpfn1ycLb/SMSdWb+SCT0WgE+cRm/gRyXYwQOcgpy+GizM77+PbcQ8rU9SecNmm8ml85SVMBYgbY0OOfyzIq8WMkMmnFpD0gNSCP57D1iTeR8h60laqKDp5Tyg==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
