apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "41.5.0"
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  releaseName: traefik
  targetNamespace: traefik
  values:
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true

    ports:
      web:
        http: {}
      websecure:
        http:
          middlewares:
            - traefik-forwarded-https@kubernetescrd

    service:
      spec:
        type: LoadBalancer
