---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB3S1TIDN1tf3BH4/4NLTY+2mtXb5h7Be9kp/j+j1hkPx6L4Z+KEjqGOiS2HFaErlC7wHbjs4Iohp8bkR2na4QvxRmfnVlJaI56+w5UZX4aVgkocgrpgHW4z68gr5JSUENl5ETj1aA550AgxwuY9p2kE7+kLIfM4+pgnrH7SoChY9J6uX67HQKEhz7oxWK9v5MTOpUg+p9YQay7xv7FAT5JnamVoJhf58T4lsigdvH4ubNAdV3PSmBhWaXvxVZZNANp3sbnPGrYx+8GaJAJfHWbXkDw6mGHUqx8Kf7BsBVLKlHBvXyWFYt3a4AwYOhNWu9RXWdjIy3ZgJVYoKI8z6pUy9fkBois+Cmzzh72r8GY9XSsjN7YZ07SFESMOy1sB2mkDouDTMKj1u0La1brmy0Bw99R1go7NTIOqEIfLyVmz+DF8U/fqYmAFZ9pp13QWhv31le3/M6ZIW0g5POTk+v/gO3dvjGitgJWPypUm5ZpU1aY3NoTlzY91rmB1TAf9y9qT6F7nQ3K57VZzExWy2MOjyG7WQr7d/J7Mz91XNyIZ0u5W1XH7QzsO4fHC6/UWhdtHow6TsxOY7Tkp3iExOnhFlKm+guTWICxh9u+KbWAg2uHMUeGydsQqdcz8UzsHQjrmbLTXyA4rUJ9QKLzJZCeCM3C0/yw3/kDmMk9Cw+QF+MzDjQMstARdAEYaHJl8piJH2MKFtqENTje+jJwTgXmmFg4rbUmRyl3dypfEsU0NBYiWyeTcsYI
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
