apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:qcE9umfvmW/b+Dc/FnR41o8gD4WUdCY7CIdMMOaSc5jYG8KYAnlXVw==,iv:BDNbcsSjHXyGIHPG1TfxdV8GtcZmigGjbmAPpEuSVHM=,tag:8fegWK5mjAWcKWKak9fZIw==,type:str]
sops:
    age:
        - recipient: age1jp7ddpkrycjnwj9slrv0hm3g4alj259df022gj6pcf2v5pnj4vuqswulmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcVpSeEF3dTBkd1FxbUkx
            RStRVjh0ZEczVzhrLzl5LzYwSE1qZ3RNWUFjCnBFSW02M3lGREkxdFUxTzhzS0c2
            S2NiMG5jOVEvaE1RSjZSR2ZwcDdZNjgKLS0tIHBwbnJmWmdUc2k3bWNhQWdTZjU1
            S0JuRnFjejBSN3Frcm5CT3g2d1hFSVkKvBWmGukIVRvj4GV0V2TYOz2KZkBRzNRs
            /qMbRSGRsYESZRFah1pgjw2jo9I0RE9T5VbyhZKe4DnyBMgIRZbQ9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T12:07:36Z"
    mac: ENC[AES256_GCM,data:PX912T4kF0h/m2Kg46tLW4aCH49ygsoeEUsbClzHyqGS5HxXJjmKUAwhONbUorBMwcFj6Tscx5naJuXRM4txTsjsW8J/BTS7r6+itJWKgQiGyx7LyrlErxH33MHXITgQ5ygr3JPzhW9uXctDfO5q9Rd8rzWmOK3uuZ82jpyR660=,iv:8AJd4UVwS+zSuEeRPfWmKg3iRNW0KxbrSxiRdsYm+iM=,tag:Q8JFIRYCJlob5zmr9KLazA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
