tunnel: 589ee03f-e779-44e2-8a72-d7b2b205d895
credentials-file: /etc/cloudflared/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
originRequest:
  noTLSVerify: true
ingress:
  - hostname: icytv.de
    service: https://traefik.traefik.svc.cluster.local:443
  - hostname: "*.icytv.de"
    service: https://traefik.traefik.svc.cluster.local:443
  - service: http_status:444
