apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homeassistant
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: base
  path: ./manifests/homeassistant
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  decryption:
    provider: sops
    secretRef:
      name: sops-age


