---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentik-sa
  namespace: authentik
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authentik-sa-admin
  namespace: authentik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: authentik-sa
    namespace: authentik
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: authentik
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: authentik-server
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
    - from:
        - podSelector: {}
  egress:
    - to:
      - podSelector:
          # This selects any pod in the 'authentik' namespace
          # that is *not* the server itself.
          matchLabels:
            app.kubernetes.io/part-of: authentik
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal
  namespace: authentik
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-authentik
  namespace: flux-system
spec:
  dependsOn:
    - name: base
  interval: 10m
  path: ./apps/authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: authentik
  serviceAccountName: authentik-sa
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age