---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared-sa
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudflared-sa-admin
  namespace: cloudflared
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: cloudflared-sa
    namespace: flux-system
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cloudflared-policy
  namespace: cloudflared
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  
  policyTypes:
    - Ingress
    - Egress

  ingress:

  # --- EGRESS (What cloudflared can talk TO) ---
  egress:
    # Allow cloudflared to talk to Traefik
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: traefik
        podSelector:
          matchLabels:
            app.kubernetes.io/name: traefik
      ports:
      - protocol: TCP
        port: 80
      - protocol: TCP
        port: 443

    # 4. Allow cloudflared to find Traefik and Cloudflare via DNS
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 53

    # 5. Allow cloudflared to connect to the Cloudflare Edge (THE TUNNEL)
    - to:
      - ipBlock:
          # Allow all internet access...
          cidr: 0.0.0.0/0
          except:
          # ...EXCEPT for internal network ranges.
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
      ports:
      - protocol: TCP
        port: 7844
      - protocol: TCP
        port: 443
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-cloudflared
  namespace: flux-system
spec:
  dependsOn:
    - name: base
  interval: 10m
  path: ./apps/cloudflared
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: cloudflared
  serviceAccountName: cloudflared-sa
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age