---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-issuer
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager
  path: ./apps/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system