---
apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homeassistant-sa
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: homeassistant-sa-admin
  namespace: homeassistant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: homeassistant-sa
    namespace: flux-system
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: homeassistant
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: homeassistant
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
      - protocol: UDP 
        port: 53
      - protocol: TCP
        port: 53
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homeassistant
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/homeassistant
  dependsOn:
    - name: base
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: homeassistant
      namespace: homeassistant
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: homeassistant
  serviceAccountName: homeassistant-sa
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ha-config-pv
  labels:
    purpose: homeassistant-config
spec:
  capacity:
    storage: 5Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/michael/.config/homeassistant
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - michael-server