apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argocd.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.0.5
    helm:
      values: |
        configs:
          params:
            server.insecure: true
          cm:
            kustomize.buildOptions: --enable-helm

            oidc.config: |
              name: Authentik
              issuer: https://auth.icytv.de/application/o/argo-cd/
              clientID: V7YyPkI3DYF2qiR145iQq2lKZmsZP9Y8Ki84XDPY
              clientSecret: $oidc.clientSecret
              requestedScopes: ["openid", "profile", "email", "groups"]
              groupsClaim: groups
          rbac:
            policy.csv: |
              g, system:authenticated, role:admin
          secret:
            oidcClientSecretExistingSecret: argocd-oidc-client
            oidcClientSecretExistingSecretKey: clientSecret
        redis:
          enabled: true
          auth:
            enabled: true
            username: default
            existingSecret: argocd-redis-password
            existingSecretPasswordKey: password
        redisSecretInit:
          enabled: false
        global:
          redis:
            username: default
            existingSecret: argocd-redis-password
            existingSecretPasswordKey: password
        server:
          secretkeyExistingSecret: argocd-server-key
          secretkeyExistingSecretKey: secretkey
          ingress:
            enabled: true
            ingressClassName: traefik
            hostname: argocd.icytv.de
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
              traefik.ingress.kubernetes.io/router.middlewares: traefik-https-redirect@kubernetescrd
              traefik.ingress.kubernetes.io/service.serversscheme: http
            tls: true
            extraTls:
              - hosts:
                  - argocd.icytv.de
                secretName: argocd-tls

          ingressGrpc:
            enabled: true
            hostname: grpc.argocd.icytv.de
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/service.serversscheme: http
            tls: true
            extraTls:
              - hosts:
                  - grpc.argocd.icytv.de
                secretName: argocd-grpc-tls

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
