# In Git: apps/argocd.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argocd.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.0.5
    helm:
      values: |
        configs:
          params:
            server.insecure: true
        server:
          ingress:
            enabled: true
            ingressClassName: traefik
            hostname: argocd.icytv.de
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/service.serversscheme: http
            tls: false

          ingressGrpc:
            enabled: true
            hostname: grpc.argocd.icytv.de
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/service.serversscheme: http
            tls: false
        redis:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
