# In Git: apps/argocd.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argocd.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 6.8.1 # Or a recent stable version
    helm:
      values: |
        server:
          ingress:
            enabled: true
            ingressClassName: traefik
            hostname: "argocd.icytv.de"
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
              traefik.ingress.kubernetes.io/service.serversscheme: "http"
            tls: false

          ingressGrpc:
            enabled: true
            hostname: "grpc.argocd.icytv.de"
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
              traefik.ingress.kubernetes.io/service.serversscheme: "http"
            tls: false


  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
