apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-extras
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/IcyTv/k8s-homelab.git
    targetRevision: HEAD
    path: manifests/traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
