apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: namespaces
  path: ./manifests/cloudflared 
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: cloudflared # Or your target namespace
  timeout: 3m