nameReference:
  - kind: ConfigMap
    fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/volumes/configMap/name

varReference:
  - kind: Deployment
    path: spec/template/spec/volumes/configMap/name
  - kind: Deployment
    path: spec/template/metadata/annotations/checksum~1config
