apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- cloudflared-credentials.yaml

configurations:
- kustomizeconfig.yaml

configMapGenerator:
- files:
  - config.yaml=config/config.yaml
  name: cloudflared-config
  options:
    annotations:
      reconciler.fluxcd.io/retain: "true"
    labels:
      app.kubernetes.io/component: tunnel
      app.kubernetes.io/instance: primary
      app.kubernetes.io/name: cloudflared

replacements:
- source:
    kind: ConfigMap
    name: cloudflared-config
    version: v1
  targets:
  - fieldPaths:
    - spec.template.metadata.annotations.checksum/config
    select:
      group: apps
      kind: Deployment
      name: cloudflared
      namespace: cloudflared
      version: v1
  - fieldPaths:
    - spec.template.spec.volumes.0.configMap.name
    select:
      group: apps
      kind: Deployment
      name: cloudflared
      namespace: cloudflared
      version: v1
