apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backstage
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: base
  path: ./manifests/backstage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: backstage
  timeout: 3m
